apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: {{ .Values.namespace }}
data:
  postgresql.conf: |
    data_directory = '/var/lib/postgresql/9.6/main'   # use data in another directory
    hba_file = '/etc/postgresql/pg_hba.conf'  # host-based authentication file
    ident_file = '/etc/postgresql/pg_ident.conf'  # ident configuration file
    external_pid_file = '/var/run/postgresql/9.6-main.pid'      # write an extra PID file

    listen_addresses = '*'      # what IP address(es) to listen on;
    port = 5432       # (change requires restart)
    max_connections = 100     # (change requires restart)

    unix_socket_directories = '/var/run/postgresql' # comma-separated list of directories

    shared_buffers = 128MB      # min 128kB

    dynamic_shared_memory_type = posix  # the default is the first option

    wal_level = hot_standby     # minimal, archive, hot_standby, or logical

    max_wal_senders = 5   # max number of walsender processes

    wal_keep_segments = 64    # in logfile segments, 16MB each; 0 disables

    hot_standby = on      # "on" allows queries during recovery

    log_line_prefix = '%t [%p-%l] %q%u@%d '     # special values:

    log_timezone = 'W-SU'

    datestyle = 'iso, mdy'

    timezone = 'W-SU'
    lc_messages = 'en_US.UTF-8'     # locale for system error message
    lc_monetary = 'en_US.UTF-8'     # locale for monetary formatting
    lc_numeric = 'en_US.UTF-8'      # locale for number formatting
    lc_time = 'en_US.UTF-8'       # locale for time formatting

    default_text_search_config = 'pg_catalog.english'

  pg_hba.conf: |
    local   all             postgres                                peer
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     peer
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            md5
    host    all             all             0.0.0.0/0               md5
    # IPv6 local connections:
    host    all             all             ::1/128                 md5
    host    replication      replication      0.0.0.0/0             trust

  pg_ident.conf: |
    # PostgreSQL User Name Maps
    # =========================
    # Put your actual configuration here
    # ----------------------------------

    # MAPNAME       SYSTEM-USERNAME         PG-USERNAME
