kind: Service
apiVersion: v1
metadata:
  name: pg-master-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    pg_master: 'true'
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432