kind: Service
apiVersion: v1
metadata:
  name: postgresql-cluster
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    name: tcp-5432
    port: 5432
    targetPort: 5432