apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgresql-cluster
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
spec:
  replicas: 2
  serviceName: "postgresql-cluster"
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: pg
        image: dharbor.gs-labs.tv/kubegres/pgnode:test
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/postgresql/9.6/main
          name: pg-volume
        - name: pg-config
          mountPath: /etc/postgresql
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
              - pg_isready
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: pg-volume
        emptyDir: {}
      - name: pg-config
        configMap:
          name: postgres-conf
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - postgresql
            topologyKey: "kubernetes.io/hostname"