apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgresql-cluster
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
spec:
  replicas: 2
  serviceName: "postgresql-cluster"
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: pg
        image: dharbor.gs-labs.tv/kubegres/pgnode:test
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/postgresql/9.6/main
          name: pg-volume
        ports:
        - containerPort: 5432
      volumes:
      - name: pg-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - postgresql
            topologyKey: "kubernetes.io/hostname"