apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pg-controller
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: pg-controller
  replicas: 1 
  template: 
    metadata:
      labels:
        app: pg-controller
    spec:
      containers:
      - name: pg-controller
        image: dharbor.gs-labs.tv/kubegres/apiserv:test
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: NAMESPACE
            value: {{ .Values.namespace }}
