kind: Service
apiVersion: v1
metadata:
  name: pg-control-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: pg-controller
  ports:
  - protocol: TCP
    name: tcp-5000
    port: 5000
    targetPort: 5000